In [1]:
import cv2
import tensorflow as tf
import numpy as np

ImportError: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by /users/sc15770/.local/lib/python3.5/site-packages/tensorflow/python/_pywrap_tensorflow.so)

In [2]:
hello_constant=tf.constant('Hello World!')
with tf.Session() as sess:
    output=sess.run(hello_constant)
    print(output)

NameError: name 'tf' is not defined

In [44]:
b=tf.ones((2,2))
print(b)

Tensor("ones_2:0", shape=(2, 2), dtype=float32)


In [45]:
with tf.Session() as sess:
    print(b.eval())

[[ 1.  1.]
 [ 1.  1.]]


In [46]:
print(b)

Tensor("ones_2:0", shape=(2, 2), dtype=float32)


In [47]:
W2=tf.Variable(tf.ones((2,2)),name="weights")
with tf.Session() as sess:
    sess.run(tf.initialize_all_variables())
    print(sess.run(W2))

[[ 1.  1.]
 [ 1.  1.]]


In [48]:
state=tf.Variable(0,name="counter")
new_value=tf.add(state,tf.constant(1))
temp=tf.mul(new_value,tf.constant(2))
update=tf.assign(state,new_value)
with tf.Session() as sess:
    sess.run(tf.initialize_all_variables())
    print(sess.run(state))
    for _ in range(3):
        print(sess.run([update,temp]))

0
[1, 2]
[2, 4]
[3, 6]


In [49]:
a=np.ones((4,4))
ta=tf.convert_to_tensor(a)
with tf.Session() as sess:
    print(sess.run(ta))

[[ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]]


In [50]:
x=tf.placeholder(tf.float32)
y=tf.placeholder(tf.float32)
z=tf.mul(x,y)
with tf.Session() as sess:
    print(sess.run([z],feed_dict={x:[7.],y:[8.]}))


[array([ 56.], dtype=float32)]


In [51]:
with tf.variable_scope("foo"):
    with tf.variable_scope("bar"):
        #k=tf.get_variable("k",[1])
        tf.get_variable_scope().reuse_variables()
        k1=tf.get_variable("k",[1])
print(k.name)
print(k1.name)

foo/bar/k:0
foo/bar/k:0
